In [1]:
import numpy as np

In [12]:
#senario 1
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)
print(a1)
print(a2)


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [13]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [14]:
#senario 2
a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)
print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [15]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [1]:
import numpy as np
a = np.array([5, 10, 15])
b = 3
# Tumhara task: a aur b ka multiplication karo

In [2]:
a*b

array([15, 30, 45])

In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])
# Tumhara task: a + b ka result print karo

In [4]:
a+b

array([[11, 22, 33],
       [14, 25, 36]])

In [5]:
a = np.array([[2],
              [4],
              [6]])
b = np.array([1, 2, 3])
# Tumhara task: a * b ka result print karo

In [6]:
a*b

array([[ 2,  4,  6],
       [ 4,  8, 12],
       [ 6, 12, 18]])