In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
arr6 = np.arange(10,15)
arr6

array([10, 11, 12, 13, 14])

In [9]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [10]:
arr9 = arr7.copy()
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [11]:
arr2.shape

(2, 3)

In [12]:
arr10 = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
arr10

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
arr10.shape

(2, 2, 2)

In [14]:
arr10.ndim

3

In [15]:
arr10.size

8

In [16]:
arr10.dtype

dtype('int64')

In [17]:
arr20 = arr10.astype("float")


In [18]:
arr10.dtype

dtype('int64')

In [19]:
arr20.dtype

dtype('float64')

In [20]:
lista = range(100)
arr11 = np.arange(100)

In [21]:
import sys

In [22]:
print(sys.getsizeof(87)*len(lista))
print(arr11.itemsize*arr11.size)

2800
800


In [23]:
import time

In [24]:
x = range(10000000)
y = range(10000000,20000000)

start_time = time.time()

c = [x+y for x,y in zip(x,y)]
print(time.time() - start_time)

1.4944682121276855


In [25]:
x = np.arange(10000000)
y = np.arange(10000000,20000000)

start_time = time.time()
c = x+y
print(time.time() - start_time)


0.21687722206115723


INDEXING ITERATION AND SCLICING

In [26]:
arr12 = np.arange(24).reshape(6,4)

In [35]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [37]:
arr12[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [41]:
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [42]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [43]:
for i in np.nditer(arr12):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [44]:
arr13 = np.array([1,2,3,4,5,6])
arr14 = np.array([7,8,9,10,11,12])

In [46]:
arr13 - arr14

array([-6, -6, -6, -6, -6, -6])

In [47]:
arr13+arr14

array([ 8, 10, 12, 14, 16, 18])

In [48]:
arr13*2

array([ 2,  4,  6,  8, 10, 12])

In [50]:
arr14 > arr13

array([ True,  True,  True,  True,  True,  True])

In [56]:
arr15 = np.arange(6).reshape(2,3)
arr16 = np.arange(6,12).reshape(3,2)

In [57]:
arr15
arr16

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [59]:
arr15.dot(arr16)

array([[ 28,  31],
       [100, 112]])

In [63]:
arr16.min()

np.int64(6)

In [65]:
arr16.min(axis=0)

array([6, 7])

In [66]:
arr16.max(axis=0)

array([10, 11])

In [69]:
arr16.min(axis=1)


array([ 6,  8, 10])

In [76]:
arr16.max(axis=1)

array([ 7,  9, 11])

In [71]:
arr16.sum(axis=0)

array([24, 27])

In [77]:
arr16.sum(axis=1)

array([13, 17, 21])

In [78]:
arr16

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [79]:
arr16.mean()

np.float64(8.5)

In [80]:
arr16.std()

np.float64(1.707825127659933)

In [81]:
arr16.ndim

2

In [82]:
arr16.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [83]:
arr16

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [95]:
arr17 = arr16.transpose()

In [96]:
import numpy as np

In [97]:
arr18 = np.arange(12,18).reshape(2,3)
arr18

array([[12, 13, 14],
       [15, 16, 17]])

In [98]:
np.hstack((arr17,arr18))

array([[ 6,  8, 10, 12, 13, 14],
       [ 7,  9, 11, 15, 16, 17]])

In [106]:
arr19 = np.vstack((arr17,arr18))
arr19

array([[ 6,  8, 10],
       [ 7,  9, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [110]:
np.vsplit(arr19,2)

[array([[ 6,  8, 10],
        [ 7,  9, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]